# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "distrib"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# See: https://readmer.dev
[package.metadata.readmer.project]
title = "Distrib"
summary = "Distrib helps you distribute your software."

[features]
default = ["all", "std"]
all = ["interop", "packaging", "runtimes", "languages"]
alloc = [
    "distrib-common/alloc",
    "distrib-macros?/alloc",
    # Packaging:
    "distrib-jsr?/alloc",
    "distrib-npm?/alloc",
    # Runtimes:
    "distrib-beam?/alloc",
    "distrib-node?/alloc",
    "distrib-wasm?/alloc",
    # Languages:
    "distrib-dart?/alloc",
    "distrib-gleam?/alloc",
    "distrib-js?/alloc",
    "distrib-python?/alloc",
    "distrib-ruby?/alloc",
    "distrib-rust?/alloc",
    # Miscellaneous:
    "dogma/alloc",
    "itertools/use_alloc",
]
cli = ["serde", "std", "clientele", "clientele/default", "clientele/tracing", "dep:clap", "dep:serde_json", "dep:toml1", "dep:tracing", "dep:tracing-subscriber"]
std = [
    "alloc",
    "distrib-common/std",
    "distrib-macros?/std",
    # Packaging:
    "distrib-jsr?/std",
    "distrib-npm?/std",
    # Runtimes:
    "distrib-beam?/std",
    "distrib-node?/std",
    "distrib-wasm?/std",
    # Languages:
    "distrib-dart?/std",
    "distrib-gleam?/std",
    "distrib-js?/std",
    "distrib-python?/std",
    "distrib-ruby?/std",
    "distrib-rust?/std",
    # Miscellaneous:
    "derive_more/std",
    "dogma/std",
]
unstable = []

# Features:
export = [
    "macros",
    # Runtimes:
    "distrib-beam?/export",
    "distrib-node?/export",
    "distrib-wasm?/export",
    # Languages:
    "distrib-dart?/export",
    "distrib-gleam?/export",
    "distrib-js?/export",
    "distrib-python?/export",
    "distrib-ruby?/export",
    "distrib-rust?/export",
]
macros = ["dep:distrib-macros"]
tracing = [
    "dep:tracing",
    "distrib-common/tracing",
    # Packaging:
    "distrib-jsr?/tracing",
    "distrib-npm?/tracing",
    # Runtimes:
    "distrib-beam?/tracing",
    "distrib-node?/tracing",
    "distrib-wasm?/tracing",
    # Languages:
    "distrib-dart?/tracing",
    "distrib-gleam?/tracing",
    "distrib-js?/tracing",
    "distrib-python?/tracing",
    "distrib-ruby?/tracing",
    "distrib-rust?/tracing",
]

# Interoperability:
interop = ["serde"]
serde = [
    "dep:serde",
    "distrib-common/serde",
    # Packaging:
    "distrib-jsr?/serde",
    "distrib-npm?/serde",
    # Runtimes:
    "distrib-beam?/serde",
    "distrib-node?/serde",
    "distrib-wasm?/serde",
    # Languages:
    "distrib-dart?/serde",
    "distrib-gleam?/serde",
    "distrib-js?/serde",
    "distrib-python?/serde",
    "distrib-ruby?/serde",
    "distrib-rust?/serde",
]

# Packaging:
packaging = ["jsr", "npm"]
jsr = ["dep:distrib-jsr"]
npm = ["dep:distrib-npm"]

# Runtimes:
runtimes = ["beam", "node", "wasm"]
beam = ["dep:distrib-beam"]
node = ["dep:distrib-node"]
wasm = ["dep:distrib-wasm"]

# Languages:
languages = ["dart", "elixir", "erlang", "gleam", "js", "python", "ruby", "rust"]
dart = ["dep:distrib-dart"]
elixir = ["beam"]
erlang = ["beam"]
gleam = ["dep:distrib-gleam", "beam"]
js = ["dep:distrib-js", "node"]
python = ["dep:distrib-python"]
ruby = ["dep:distrib-ruby"]
rust = ["dep:distrib-rust"]

[dependencies]
derive_more = { workspace = true, features = ["display", "from_str"] }
dogma.workspace = true
glob.workspace = true
itertools.workspace = true
thiserror.workspace = true

# Features:
distrib-common.workspace = true
distrib-macros = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

# Interoperability:
serde = { workspace = true, optional = true }

# Packaging:
distrib-jsr = { workspace = true, optional = true }
distrib-npm = { workspace = true, optional = true }

# Runtimes:
distrib-beam = { workspace = true, optional = true }
distrib-node = { workspace = true, optional = true }
distrib-wasm = { workspace = true, optional = true }

# Languages:
distrib-dart = { workspace = true, optional = true }
distrib-gleam = { workspace = true, optional = true }
distrib-js = { workspace = true, optional = true }
distrib-python = { workspace = true, optional = true }
distrib-ruby = { workspace = true, optional = true }
distrib-rust = { workspace = true, optional = true }

# CLI:
clap = { workspace = true, optional = true }
clientele = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
toml1 = { workspace = true, optional = true, features = ["parse", "serde"] }
tracing-subscriber = { workspace = true, optional = true }

[[bin]]
name = "distrib"
path = "src/main.rs"
required-features = ["cli"]

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See: https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md
[package.metadata.binstall]
disabled-strategies = ["quick-install"]
