# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "distrib"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# See: https://readmer.dev
[package.metadata.readmer.project]
title = "Distrib"
summary = "Distrib helps you distribute your software."

[features]
default = ["all", "std"]
all = ["interops", "languages"]
alloc = [
    "distrib-macros?/alloc",
    "distrib-beam?/alloc",
    "distrib-dart?/alloc",
    "distrib-gleam?/alloc",
    "distrib-js?/alloc",
    "distrib-python?/alloc",
    "distrib-ruby?/alloc",
    "distrib-rust?/alloc",
    "distrib-wasm?/alloc",
    "dogma/alloc",
]
cli = ["std", "clientele", "clientele/default", "clientele/tracing", "dep:clap"]
std = [
    "alloc",
    "derive_more/std",
    "distrib-macros?/std",
    "distrib-beam?/std",
    "distrib-dart?/std",
    "distrib-gleam?/std",
    "distrib-js?/std",
    "distrib-python?/std",
    "distrib-ruby?/std",
    "distrib-rust?/std",
    "distrib-wasm?/std",
    "dogma/std",
]
unstable = []

# Features:
export = ["macros"]
macros = [
    "distrib-beam?/rustler",
    "distrib-dart?/dart-sys",
    #"distrib-gleam?/",
    "distrib-js?/napi",
    "distrib-python?/pyo3",
    "distrib-ruby?/magnus",
    #"distrib-rust?/",
    "distrib-wasm?/wasm-bindgen",
    "dep:distrib-macros",
]

# Interoperability:
interops = ["serde"]
serde = [
    "distrib-beam?/serde",
    "distrib-dart?/serde",
    "distrib-gleam?/serde",
    "distrib-js?/serde",
    "distrib-python?/serde",
    "distrib-ruby?/serde",
    "distrib-rust?/serde",
    "distrib-wasm?/serde",
]

# Languages:
languages = ["beam", "dart", "gleam", "js", "python", "ruby", "rust", "wasm"]
beam = ["distrib-macros?/beam", "dep:distrib-beam"]
dart = ["distrib-macros?/dart", "dep:distrib-dart"]
gleam = ["beam", "dep:distrib-gleam"]
js = ["distrib-macros?/js", "dep:distrib-js"]
python = ["distrib-macros?/python", "dep:distrib-python"]
ruby = ["distrib-macros?/ruby", "dep:distrib-ruby"]
rust = ["distrib-macros?/rust", "dep:distrib-rust"]
wasm = ["distrib-macros?/wasm", "dep:distrib-wasm"]

# Language aliases:
elixir = ["beam"]
erlang = ["beam"]

[dependencies]
derive_more = { workspace = true, features = ["display", "from_str"] }
dogma.workspace = true
thiserror.workspace = true

# Features:
distrib-macros = { workspace = true, optional = true }

# Languages:
distrib-beam = { workspace = true, optional = true }
distrib-dart = { workspace = true, optional = true }
distrib-gleam = { workspace = true, optional = true }
distrib-js = { workspace = true, optional = true }
distrib-python = { workspace = true, optional = true }
distrib-ruby = { workspace = true, optional = true }
distrib-rust = { workspace = true, optional = true }
distrib-wasm = { workspace = true, optional = true }

# CLI:
clap = { version = "4.5", default-features = false, optional = true }
clientele = { version = "0.3.8", features = [], optional = true }

[[bin]]
name = "distrib"
path = "src/main.rs"
required-features = ["cli"]

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See: https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md
[package.metadata.binstall]
disabled-strategies = ["quick-install"]
