# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "distrib-build"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# See: https://readmer.dev
[package.metadata.readmer.project]
title = "Distrib: Build"
summary = "Distrib helps you distribute your software."

[features]
default = ["all", "std"]
all = ["languages"]
alloc = []
std = ["alloc"]
unstable = []

# Languages:
languages = ["dart", "js", "python", "ruby", "rust", "wasm"]
dart = []
js = []
python = ["dep:pyo3-build-config"]
ruby = []
rust = []
wasm = []

[dependencies]

# Languages:
pyo3-build-config = { workspace = true, optional = true }

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
