# See: https://gleam.run/writing-gleam/gleam-toml/

name = "distrib"
version = "0.0.0"

description = "Distrib for BEAM"
licences = ["Unlicense"]
repository = { type = "github", user = "artob", repo = "distrib" }
links = [{ title = "Website", href = "https://distrib.sh" }]

[dependencies]
child_process = ">= 2.1.2 and < 3.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
