# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "0.0.0"
authors = ["Arto Bendiken"]
edition = "2024"
rust-version = "1.85"
description = "Distrib helps you distribute your software."
#documentation = "https://docs.rs/distrib"
readme = true
homepage = "https://distrib.sh"
repository = "https://github.com/artob/distrib"
license = "Unlicense"
keywords = ["distrib"]
categories = ["command-line-utilities", "no-std"]
publish = true

[workspace]
members = ["lib/*"]
resolver = "2"

[workspace.dependencies]
distrib = { version = "=0.0.0", default-features = true }
distrib-dart = { version = "=0.0.0", default-features = true }
distrib-js = { version = "=0.0.0", default-features = true }
distrib-python = { version = "=0.0.0", default-features = true }
distrib-ruby = { version = "=0.0.0", default-features = true }
distrib-rust = { version = "=0.0.0", default-features = true }

# Implementation:
cargo_toml = { version = "1.0", default-features = false }
derive_more = { version = "2", default-features = false }
dogma = { version = "0.2.1", default-features = false }
package_json_schema = { version = "0.3", default-features = false }
pyproject-toml = { version = "0.13", default-features = false }
serde_norway = { version = "0.9", default-features = false }
thiserror = { version = "2", default-features = false }

# Interoperability:
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["preserve_order"] }
serde_with = { version = "3.21", default-features = false, features = ["macros"] }
toml0 = { package = "toml", version = "0.9", default-features = false }
toml1 = { package = "toml", version = "1.0", default-features = false }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[patch.crates-io]
distrib = { path = "lib/distrib" }
distrib-dart = { path = "lib/distrib-dart" }
distrib-js = { path = "lib/distrib-js" }
distrib-python = { path = "lib/distrib-python" }
distrib-ruby = { path = "lib/distrib-ruby" }
distrib-rust = { path = "lib/distrib-rust" }
