# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "0.0.0"
authors = ["Arto Bendiken"]
edition = "2024"
rust-version = "1.85"
description = "Distrib helps you distribute your software."
#documentation = "https://docs.rs/distrib"
readme = true
homepage = "https://distrib.sh"
repository = "https://github.com/artob/distrib"
license = "Unlicense"
keywords = ["distrib"]
categories = ["command-line-utilities", "api-bindings", "development-tools::ffi", "no-std"]
publish = true

[workspace]
members = ["lib/*"]
resolver = "2"

[workspace.dependencies]
distrib = { version = "=0.0.0", default-features = true }
distrib-build = { version = "=0.0.0", default-features = true }
distrib-macros = { version = "=0.0.0", default-features = true }

# Languages:
distrib-dart = { version = "=0.0.0", default-features = true }
distrib-js = { version = "=0.0.0", default-features = true }
distrib-python = { version = "=0.0.0", default-features = true }
distrib-ruby = { version = "=0.0.0", default-features = true }
distrib-rust = { version = "=0.0.0", default-features = true }
distrib-wasm = { version = "=0.0.0", default-features = true }

# Languages - Dart:
dart-sys = { version = "4.1.5", default-features = false }

# Languages - JS/TS:
napi = { version = "3.4", default-features = false }
napi-build = { version = "2.2.4", default-features = false }
napi-derive = { version = "3.3", default-features = false }
neon = { version = "1.1.1", default-features = false }
package_json_schema = { version = "0.3", default-features = false }

# Languages - Python:
pyo3 = { version = "0.29", default-features = false }
pyo3-build-config = { version = "0.29", default-features = false }
pyproject-toml = { version = "0.13", default-features = false }

# Languages - Ruby:
magnus = { version = "0.8.2", default-features = false }
rb-sys = { version = "0.9.128", default-features = false }
rb-sys-build = { version = "0.9.128", default-features = false }

# Languages - Rust:
cargo_toml = { version = "1.0", default-features = false }

# Languages - WebAssembly:
wasm-bindgen = { version = "0.2.126", default-features = false }

# Miscellaneous:
derive_more = { version = "2", default-features = false }
dogma = { version = "0.2.1", default-features = false }
serde_norway = { version = "0.9", default-features = false }
thiserror = { version = "2", default-features = false }

# Interoperability:
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["preserve_order"] }
serde_with = { version = "3.21", default-features = false, features = ["macros"] }
toml0 = { package = "toml", version = "0.9", default-features = false }
toml1 = { package = "toml", version = "1.0", default-features = false }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[patch.crates-io]
distrib = { path = "lib/distrib" }
distrib-build = { path = "lib/distrib-build" }
distrib-macros = { path = "lib/distrib-macros" }
distrib-dart = { path = "lib/distrib-dart" }
distrib-js = { path = "lib/distrib-js" }
distrib-python = { path = "lib/distrib-python" }
distrib-ruby = { path = "lib/distrib-ruby" }
distrib-rust = { path = "lib/distrib-rust" }
distrib-wasm = { path = "lib/distrib-wasm" }
